# Generated by Django 4.1.6 on 2023-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.TextField()),
                ('flatType', models.TextField()),
                ('flatModel', models.TextField()),
                ('floorArea', models.TextField()),
                ('floor', models.TextField()),
                ('a', models.TextField()),
                ('remainingLease', models.TextField()),
            ],
        ),
    ]
