# Generated by Django 4.1.6 on 2023-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='flatModel',
        ),
    ]
